config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"
  # resources :users, :only => [:index, :show, :edit, :update ]
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  
  resources :resumes, :except => [:destroy]
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  belongs_to :user

  serialize :summary
  serialize :work_experience
  serialize :education
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name

  has_many :resumes

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.consumer_token = auth['credentials']['token']
      user.consumer_secret = auth['credentials']['secret']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
         user.location = auth['info']['location'] || ""
         user.image_url = auth['info']['image'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private

    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController

  def index
    authenticate_user!
    @resume = Resume.where(user_id: current_user.id).first
  end

  def create
    authenticate_user!
    @client = LinkedIn::Client.new
    @client.authorize_from_access(current_user.consumer_token, current_user.consumer_secret)
    @resume = Resume.create do |u|
      u.location = current_user.location
      u.picture_url = current_user.image_url
      u.summary = @client.profile(:fields => %w(summary))
      u.work_experience = @client.profile(:fields => %w(positions))
      u.education = @client.profile(:fields => %w(educations))
      u.user = current_user
    end
    
    if @resume.save
      flash[:notice] = "Resume Saved!"
      redirect_to resumes_path
    else
      flash[:success] = "Resume did not save."
      redirect_to resumes_path
    end
  end

  def show
    @resume = Resume.where(user_id: current_user.id).first
  end

  private

  def resume_params
    params.require(:resume).permit(:location, :current_status, :picture_url, :summary, :work_experience, :education, :current_status_timestamp)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/linkedin'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    # Reset the session after successful login, per
    # 2.8 Session Fixation – Countermeasures:
    # http://guides.rubyonrails.org/security.html#session-fixation-countermeasures
    reset_session
    session[:user_id] = user.id
    if user.email.blank?
      redirect_to edit_user_path(user), :alert => "Please enter your email address."
    else
      redirect_to resumes_path, :notice => 'Signed in!'
    end

  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

    def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def secure_params
    params.require(:user).permit(:email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/home/index.html.erb
<h3>Home</h3>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Resume', resumes_path %></li>
  <li><%= link_to 'Logout', signout_path %></li>
<% else %>
  <li><%= link_to 'Login', signin_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rsm" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rsm" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/resumes/index.html.erb
<h1>Resumes</h1>

<br />

<% if @resume.nil? %>
  <%= link_to "Import Your Linkedin Resume", resumes_path, method: :post %> <br />
  You currently do not have a Resume added.
<% else %>
  <li>Resume <%= link_to "[VIEW]", resume_path(@resume) %></li>
<% end %>

app/views/resumes/show.html.erb
<img align="left" src=<%= current_user.image_url %> /> 
  <h2><%= current_user.name %></h2>
<br/>
<br />
<h3>Contact Information:</h3>
<b>Email:</b> <%= current_user.email %>
<br />
<h3>Summary:</h3>
<%= @resume.summary.first[1] %>
<br />
<br />
<h3>Work Experience: </h3> <br>
  <% companies = @resume.work_experience.positions.all.map{|t| t.company } %>
  <% summaries = @resume.work_experience.positions.all.map{|t| t.summary } %>
  <% start_time = @resume.work_experience.positions.all.map{|t| t.start_date }%>
  <% end_time = @resume.work_experience.positions.all.map{|t| t.end_date } %>

  <% companies.zip(summaries, start_time, end_time).each do |z, x, c, v| %>
    <b><%= z.name %></b> <br />
      <%= Date::MONTHNAMES[c.month] %>, 
        <%= c.year %>  - 
        <% if !v.nil? %>
          <%= Date::MONTHNAMES[v.month] %>,
          <%= v.year %><br />
        <% else %>
          Current <br />
        <% end %>
        <br />
      <%= x %> <br /> <br />
  <% end %>

<h3>Education:</h3>
  <% education = @resume.education.educations.all %>
  <% education.each do |x| %>
    <%= x.school_name %> <br />
    <% if !x.degree.blank? %>
      <%= x.degree %> <br />
    <% end %>
    <%= x.start_date.year %> - <%= x.end_date.year %><br /><br />
  <% end %>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br />
  <%= f.submit "Update" %>
<% end %>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<%= link_to 'Edit account', edit_user_path %>